// 选项越小（A）越能承受风险
export const questions = [
    { id: 1, text: "What is your age?", options: ["A. 18-30", "B. 31-45", "C. 46-60", "D. 61-75", "E. 76 or above"], weight: 1 },
    { id: 2, text: "What is your income source?", options: ["A. Fixed income (e.g., salary, pension) ", "B. Mixed (fixed and variable sources)", "C. Variable (e.g., freelance, commissions) ", "D. Passive income (e.g., investments, rental)", "E. No income"], weight: 2 },
    { id: 3, text: "Annual investment amount?", options: ["A. Above $500,000", "B. $200,000 - $500,000", "C. $50,000 - $200,000", "D. $10,000 - $50,000", "E. Below $10,000"], weight: 2 },
    { id: 4, text: "Your next major expenditure?", options: ["A. Capitalizing a new business (large, uncertain risk)", " B. Buying property (significant financial commitment)", " C. Paying for higher education (moderate-long time horizon)", " D. Providing for retirement (longer-term, cautious)", " E. Urgent or medical expenses (must preserve capital)"], weight: 2 },
    { id: 5, text: "Your primary objective for investing?", options: ["A. Focus on high long-term returns, ignoring short-term volatility", "B. Long-term growth, tolerant of short-term fluctuations", "C. Moderate appreciation with balanced risk", "D. Ensure asset security with fixed returns", "E. Solely preserve capital (very limited risk tolerance)"], weight: 3 },
    { id: 6, text: "When do you expect to use your investment money?", options: ["A. Beyond 20 years", "B. In 11-20 years", "C. In 6-10 years", "D. In 2-5 years", "E. Any time now (high liquidity needed)"], weight: 2 },
    { id: 7, text: "Expected annual income change?", options: ["A. Substantial growth", "B. Moderate growth", "C. Stay the same", "D. Moderate decrease", "E. Substantial decrease"], weight: 2 },
    { id: 8, text: "Your level of financial knowledge?", options: ["A. Thorough understanding with advanced techniques", "B. Fair understanding with some investment techniques", "C. Some understanding but no investment skills", "D. Lack basic investment knowledge", "E. No knowledge and refuse to learn"], weight: 2 },
    { id: 9, text: "Years of experience investing in risk assets?", options: ["A. Over 8 years", "B. 5-8 years", "C. 2-5 years", "D. Under 2 years", "E. None"], weight: 2 },
    { id: 10, text: "How do you perceive investment losses?", options: ["A. Indifferent, not concerned about losses", "B. Completely normal, accepts risks", "C. Neutral mindset, little emotional effect", "D. Some impact but manageable", "E. Very difficult to accept"], weight: 3 },
    { id: 11, text: "Response after a 14% investment loss due to market correction?", options: ["A. Buy more at a lower price", "B. Hold and wait for recovery", "C. Ignore short-term fluctuations and stick to the long-term plan", "D. Reassess the investment strategy before taking action", "E. Sell to avoid further decline"], weight: 3 },
    { id: 12, text: "Maximum acceptable loss percentage?", options: ["A. Above 55%", "B. 40%-55%", "C. 25%-40%", "D. 10%-25%", "E. Within 10%"], weight: 3 },
    { id: 13, text: "Expected investment return rate?", options: ["A. Over 20%, high risk", "B. 10-20%, moderate risk", "C. Around 10%, low risk", "D. Higher than fixed deposit rate", "E. Capital preservation is the priority, minimal return expected"], weight: 3 },
    { id: 14, text: "Investing plan for your portfolio?", options: ["A. High-risk, highest returns", "B. Moderate risk, high returns", "C. Diversify across all risk levels", "D. Low-risk, stable returns", "E. Focus on capital preservation with minimal risk"], weight: 3 },
    { id: 15, text: "Preferred stock investment type?", options: ["A. High-growth potential, low price, high risk", "B. Established growth companies with moderate risk", "C. Blue-chip dividend stocks with stable returns", "D. Defensive sector stocks with low volatility", "E. Capital-preservation focused stocks with minimal risk"], weight: 3 },
    { id: 16, text: "Preferred bond investment type?", options: ["A. High-yield (junk) bond, highest risk", "B. Corporate bond from emerging companies, moderate-high risk", "C. Corporate bond from established companies, moderate risk", "D. Government municipal bond, low risk", "E. Treasury bond or equivalent, minimal risk"], weight: 3 },
    { id: 17, text: "Response to inflation advice with long-term bonds?", options: ["A. Ignore advice and maintain bond holdings, highest risk", "B. Small partial shift to hard assets, moderate-high risk", "C. Balanced shift between bonds and hard assets, moderate risk", "D. Major shift to hard assets, low risk", "E. Complete exit from bonds in favor of inflation-protected assets, minimal risk"], weight: 3 },
    { id: 18, text: "Game show decision with $10,000 winnings?", options: ["A. Reject $10,000 and aim for maximum prize regardless of odds, highest risk", "B. 5% chance to win $100,000, high risk", "C. 20% chance to win $75,000, moderate-high risk", "D. 50% chance to win $50,000, moderate risk", "E. Take the guaranteed $10,000, no risk"], weight: 3 }
];

